dbname update
replacing "${spring.data.mongodb.database}" with "vyiradb" due to connectivity failure in because of dbname with below exception.

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [com/vyira/vyirasuite/quizserver/config/ApplicationMongoDBConfiguration.class]: U
nsatisfied dependency expressed through method 'mongoTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDbFactory' defined in class path re
source [com/vyira/vyirasuite/quizserver/config/ApplicationMongoDBConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instant
iate [org.springframework.data.mongodb.MongoDatabaseFactory]: Factory method 'mongoDbFactory' threw exception; nested exception is java.lang.IllegalArgumentException: Database name must not contain slashes, dots, spaces, quo
tes, or dollar signs!