Enabled Eureka Server-Client
Changed following.
1. application.yml -> Port number of each sub module
2. Dockerfile -> Corresponding port number updated in Dockerfile
3. Added @EnableDiscoveryClient annotation in each application main file.
4. Added Eureka Server module
5. Created ServiceInstanceRestController for Clients to register with Discovery server
6. Updated pom.xml, adding respective dependencies (Spring cloud)
7. Renamed DefaultController.java to GenericController for Better naming convention.

Adding discovery-server

Added new Module in the project as discovery server
i.e. Netflix Eureka Server for Microservices Discovery Server

Eureka Client Dependency added

Dockerfile for discovery-server

CustomProperties

Defining new Custom Properties in application.yml file.

dbname update

replacing "${spring.data.mongodb.database}" with "vyiradb" due to connectivity failure in because of dbname with below exception.

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [com/vyira/vyirasuite/quizserver/config/ApplicationMongoDBConfiguration.class]: U
nsatisfied dependency expressed through method 'mongoTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDbFactory' defined in class path re
source [com/vyira/vyirasuite/quizserver/config/ApplicationMongoDBConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instant
iate [org.springframework.data.mongodb.MongoDatabaseFactory]: Factory method 'mongoDbFactory' threw exception; nested exception is java.lang.IllegalArgumentException: Database name must not contain slashes, dots, spaces, quo
tes, or dollar signs!

eslintcache

Controller Updated

Modified for Middleware service

Better Skeleton Creation

Models Update

Updating Models of applications along with the name of collection
names for each model.

Configuration for MongoDB

returning database name mentioned in application.yml

Adding Repository Interface

QuestionRepository and QuizRepository is added to let spring-data-mongo
can interact with mongodb.

Fixed incorrect annotation usage

Replacing Answer[] with List<Answer>

Mongo Driver dependency added

renaming class

Dockerfile